### ISSUE TITLE
Deploy subgraph for Polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveconomy-subgraph#75]

**Comment by laurenluz** [comment]
Hey @geleeroyale @mhmdksh - we are ready to deploy the subgraph for polygon zkevm testnet cardona!

And if it's easy to do in one shot, would be great to also deploy for polygon zkevm

https://thegraph.com/docs/en/developing/supported-networks/

**Comment by geleeroyale** [comment]
As soon as its added to the code in this repo we can deploy it.

**Comment by geleeroyale** [comment]
Giveconomy subgraph for zkEVM Cardona testnet has been deployed as `giveconomy-zkevm`

still needed:
- givback calculation
- givpower production

**Comment by laurenluz** [comment]
we have also deployed the subgraph for zkEVM mainnet? @geleeroyale @mohammadranjbarz ?

**Comment by mohammadranjbarz** [comment]
> we have also deployed the subgraph for zkEVM mainnet? @geleeroyale @mohammadranjbarz ?

Yes we did and it's working fine
